"""Extract public ICU 67.1 frequency tables for the portable C recognizer.

Pass the directory containing CharsetRecog_sbcs.java and CharsetRecog_mbcs.java
from unicode-org/icu release-67-1, icu4j/main/classes/core/src/com/ibm/icu/text.
No Java code executes at build time or runtime.
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODELS = [
    ('8859_1', 'ISO-8859-1', 'windows-1252'),
    ('8859_2', 'ISO-8859-2', 'windows-1250'),
    ('8859_5_ru', 'ISO-8859-5', ''), ('8859_6_ar', 'ISO-8859-6', ''),
    ('8859_7_el', 'ISO-8859-7', 'windows-1253'),
    ('8859_8_I_he', 'ISO-8859-8-I', 'windows-1255'),
    ('8859_8_he', 'ISO-8859-8', 'windows-1255'),
    ('windows_1251', 'windows-1251', ''), ('windows_1256', 'windows-1256', ''),
    ('KOI8_R', 'KOI8-R', ''), ('8859_9_tr', 'ISO-8859-9', 'windows-1254'),
]


def without_comments(text):
    return re.sub(r'/\*.*?\*/|//[^\n]*', '', text, flags=re.S)


def values(text):
    return re.findall(r'0x[0-9a-fA-F]+', text)


def lines_of_values(items, indent='    '):
    return '\n'.join(indent + ','.join(items[i:i+8]) + ','
                     for i in range(0, len(items), 8))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source_directory', type=Path)
    args = parser.parse_args()
    text = without_comments((args.source_directory/'CharsetRecog_sbcs.java').read_text())
    blocks = {}
    for match in re.finditer(r'(?:abstract\s+)?static\s+class\s+(\w+)\s+extends\s+(\w+)\s*\{', text):
        start = pos = match.end()
        depth = 1
        while depth:
            if text[pos] == '{': depth += 1
            if text[pos] == '}': depth -= 1
            pos += 1
        blocks[match[1]] = (match[2], text[start:pos-1])
    output = ['/* Unicode ICU 67.1 statistical tables, under vendor/icu_charset/LICENSE.',
              '   Generated by validation/generate_cimport_charsets.py. */']
    rows = []
    for index, (suffix, name, c1name) in enumerate(MODELS):
        parent, body = blocks['CharsetRecog_'+suffix]
        maps = re.findall(r'byteMap\s*=\s*\{([^{}]*)\}', body, re.S)
        if not maps:
            maps = re.findall(r'byteMap\s*=\s*\{([^{}]*)\}', blocks[parent][1], re.S)
        mapping = values(maps[0])
        assert len(mapping) == 256
        grams = [values(v) for v in re.findall(r'\{([^{}]*)\}', body, re.S)]
        grams = [g for g in grams if len(g) == 64]
        assert grams and all(g == sorted(g, key=lambda x: int(x, 16)) for g in grams)
        output.append(f'static const unsigned char charset_map_{index}[256]={{\n'+lines_of_values(mapping)+'\n};')
        output.append(f'static const uint32_t charset_grams_{index}[{len(grams)}][64]={{\n'+
                      ',\n'.join('  {\n'+lines_of_values(g)+'\n  }' for g in grams)+'\n};')
        rows.append(f'    {{"{name}","{c1name}",charset_map_{index},charset_grams_{index},{len(grams)}}},')
    output.append('static const charset_sbcs_model charset_sbcs_models[]={\n'+'\n'.join(rows)+'\n};')
    text = without_comments((args.source_directory/'CharsetRecog_mbcs.java').read_text())
    for index, suffix in enumerate(['sjis', 'gb_18030', 'euc_jp', 'euc_kr', 'big5']):
        body = text.split('class CharsetRecog_'+suffix)[1]
        array = re.search(r'commonChars\s*=\s*\{([^{}]*)\}', body, re.S)
        common = values(array[1])
        assert common == sorted(common, key=lambda x: int(x, 16))
        output.append(f'static const uint32_t charset_common_{index}[]={{\n'+lines_of_values(common)+'\n};')
    (ROOT/'src/cimport/cimport_charset_tables.inc').write_text('\n'.join(output)+'\n')
    print('Generated 11 single-byte models and 5 multibyte frequency tables')


if __name__ == '__main__':
    main()
