* Generated by suite_registry.py --write-master; edit suites.json.
local scripts "csort cmerge cimport cexport creghdfe cqreg civreghdfe cdecode cencode cdestring csample cbsample cbinscatter cpsmatch crangestat cwinsor cpplmhdfe cipolate csplit crangejoin audit_p1 audit_p2 sep22 sep24 memory_safety command_optimizations"
