"""Generate release identity from release.json; --check rejects stale copies."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def generated():
    release = json.loads((ROOT / "release.json").read_text())
    v, date, minimum = (release[k] for k in ("version", "date", "stata_minimum"))
    files = {}
    files["src/ctools_version.h"] = f'''/* Generated by scripts/sync_release.py from release.json. */
#ifndef CTOOLS_VERSION_H
#define CTOOLS_VERSION_H
#define CTOOLS_VERSION "{v}"
#define CTOOLS_RELEASE_DATE "{date}"
#ifndef CTOOLS_BUILD_REVISION
#define CTOOLS_BUILD_REVISION "local"
#endif
#endif
'''
    for filename in ("README.md", "build/ctools.ado", "build/ctools.sthlp", "build/ctools.pkg"):
        text = (ROOT / filename).read_text()
        if filename == "README.md":
            text = re.sub(r"!\[Version\]\([^\n]+\)", f"![Version](https://img.shields.io/badge/version-{v}-blue)", text)
        elif filename.endswith(".ado"):
            text = re.sub(r"^\*! version .*", f"*! version {v} {date} github.com/mdroste/stata-ctools", text)
            text = re.sub(r"\{col 56\}v[\d.]+", f"{{col 56}}v{v}", text)
            text = re.sub(r'local __ado_version "[\d.]+"', f'local __ado_version "{v}"', text)
        elif filename.endswith(".sthlp"):
            text = re.sub(r"\{\* \*! version [^}]+\}", f"{{* *! version {v} {date}}}", text)
        else:
            text = re.sub(r"(?m)^d Version: .*$", f"d Version: {v}", text)
            text = re.sub(r"(?m)^d Requires: .*$", f"d Requires: Stata {minimum} or later", text)
            text = re.sub(r"(?m)^d Distribution-Date: .*$", f"d Distribution-Date: {date}", text)
        files[filename] = text
    for filename in ("LICENSE", "THIRD_PARTY_NOTICES"):
        files[f"build/{filename}"] = (ROOT / filename).read_text()
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for name, content in generated().items():
        path = ROOT / name
        if not path.exists() or path.read_text() != content:
            if args.check: stale.append(name)
            else: path.write_text(content)
    if stale: raise SystemExit("Stale release metadata: " + ", ".join(stale))
    print("Release metadata checked" if args.check else "Release metadata synchronized")


if __name__ == "__main__":
    main()
