* Test: Run full validation sequence like validate_all.do
clear all
set more off
adopath ++ "build"
adopath ++ "../build"

di "Testing csort..."
capture noisily quietly do "validation/validate_csort.do"
di "Testing cmerge..."
capture noisily quietly do "validation/validate_cmerge.do"
di "Testing cimport..."
capture noisily quietly do "validation/validate_cimport.do"
di "Testing cexport..."
capture noisily quietly do "validation/validate_cexport.do"
di "Testing creghdfe..."
capture noisily quietly do "validation/validate_creghdfe.do"
di "Testing cqreg..."
capture noisily quietly do "validation/validate_cqreg.do"
di "Testing civreghdfe..."
capture noisily quietly do "validation/validate_civreghdfe.do"
di "Testing cdecode..."
capture noisily quietly do "validation/validate_cdecode.do"
di "Testing cencode..."
capture noisily quietly do "validation/validate_cencode.do"
di "Testing cdestring..."
capture noisily quietly do "validation/validate_cdestring.do"
di "Testing csample..."
capture noisily quietly do "validation/validate_csample.do"
di "Testing cbsample..."
capture noisily quietly do "validation/validate_cbsample.do"
di "Testing cbinscatter..."
capture noisily quietly do "validation/validate_cbinscatter.do"
di "Testing cpsmatch..."
capture noisily quietly do "validation/validate_cpsmatch.do"
di "Testing crangestat..."
capture noisily quietly do "validation/validate_crangestat.do"

di "All validations complete!"
