"""Authoritative correctness inventory shared by local gates, Stata, and CI."""
from pathlib import Path
import argparse
import json
import os
import platform
import subprocess
import sys
from stata_runner import ROOT, run_do

REGISTRY = ROOT / 'validation/suites.json'
MASTER = ROOT / 'validation/suites_master.do'


def load_registry():
    return json.loads(REGISTRY.read_text())['suites']


def master_names():
    return [s['name'] for s in load_registry() if s['runner'] == 'master']


def master_source():
    return '* Generated by suite_registry.py --write-master; edit suites.json.\nlocal scripts "' + ' '.join(master_names()) + '"\n'


def check_registry():
    suites = load_registry()
    paths = [s['path'] for s in suites]
    if len(paths) != len(set(paths)):
        raise ValueError('duplicate suite paths')
    discovered = {str(p.relative_to(ROOT)) for pattern in ('validate_*.do', 'test_*.do', 'test_*.py', 'benchmark_*.do', 'benchmark_*.py')
                  for p in (ROOT / 'validation').glob(pattern)}
    if set(paths) != discovered:
        raise ValueError(f'registry mismatch: missing={discovered-set(paths)}, stale={set(paths)-discovered}')
    for s in suites:
        for key in ('name', 'runner', 'category', 'fixtures', 'dependencies', 'marker'):
            if key not in s:
                raise ValueError(f'{s["path"]}: missing {key}')
        if s['runner'] in ('helper', 'manual') and not s.get('reason'):
            raise ValueError(f'{s["path"]}: exclusion needs a reason')
        if s['runner'] in ('master', 'do', 'python') and not s['marker']:
            raise ValueError(f'{s["path"]}: missing completion marker')
    if not MASTER.exists() or MASTER.read_text() != master_source():
        raise ValueError('stale Stata registry; run suite_registry.py --write-master')


def transport_fixture():
    out = ROOT / 'temp/registry_transport'
    # This prepares a real SPI test plugin; it does not execute the benchmark.
    subprocess.run([sys.executable, str(ROOT/'validation/benchmark_transport.py'),
                    '--variant', f'current={ROOT / "src"}', '--output', str(out),
                    '--rows', '1', '--columns', '1', '--repetitions', '1'], cwd=ROOT, check=True)
    return out / 'current.plugin'


def run_extra_stata():
    check_registry()
    logs = ROOT / 'temp/registry_logs'
    logs.mkdir(parents=True, exist_ok=True)
    for suite in load_registry():
        if suite['category'] != 'correctness' or suite['runner'] not in ('python', 'do'):
            continue
        print('Running ' + suite['name'], flush=True)
        if suite['runner'] == 'python':
            subprocess.run([sys.executable, *suite['command'][1:]], cwd=ROOT, check=True)
        else:
            args = [transport_fixture()] if 'transport-plugin' in suite['fixtures'] else []
            run_do(ROOT/suite['path'], logs/(suite['name']+'.log'), args, [suite['marker']])


def run_native():
    check_registry()
    for suite in load_registry():
        if suite['runner'] != 'native':
            continue
        env = os.environ.copy()
        # ASan policy matches the Linux gate; macOS suites choose their supported
        # defaults unless the caller explicitly asks for a sanitizer override.
        if platform.system() == 'Linux':
            for key, value in suite.get('env', {}).items(): env.setdefault(key, value)
        print('Running ' + suite['name'], flush=True)
        subprocess.run([sys.executable, str(ROOT/suite['path'])], cwd=ROOT, env=env, check=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write-master', action='store_true')
    parser.add_argument('--native', action='store_true')
    parser.add_argument('--extra-stata', action='store_true')
    parser.add_argument('--list', action='store_true')
    args = parser.parse_args()
    if args.write_master: MASTER.write_text(master_source())
    check_registry()
    if args.list:
        for s in load_registry(): print(s['category'], s['runner'], s['path'], s.get('reason', ''))
    if args.native: run_native()
    if args.extra_stata: run_extra_stata()
    print('Validation registry checked')


if __name__ == '__main__': main()
